services:
  ludiscan-webapp:
    networks:
      - ludiscan-network
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: ludiscan-webapp
    ports:
      - "3003:3000"
    restart: always
    tty: true

networks:
  ludiscan-network:
    driver: bridge
